version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Docker...
      - nohup /usr/local/bin/dockerd-entrypoint.sh &  # Start Docker Daemon
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 382828593676.dkr.ecr.us-east-1.amazonaws.com)
      - echo Building the application with Maven...
      - mvn clean package -DskipTests

  build:
    commands:
      - echo Building Docker image...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:$IMAGE_TAG .
      - docker tag 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:$IMAGE_TAG 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:$IMAGE_TAG
      - docker push 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:latest
      - echo Writing image definitions file...
      - printf '[{"name":"service1","imageUri":"%s"}]' 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
